version: "3.8"
services:
  # user product service
  user-app:
    container_name: user-app
    build: 
      context: ./users
      dockerfile: ./Dockerfile
      args:
        DB_PORT: 5432
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - api
    depends_on:
      - user-db
    links:
      - user-db
    volumes:
      - ./users:/home/www/webapp
      - /home/www/webapp/node_modules
  # publication product service
  publication-app:
    container_name: publication-app
    build: 
      context: ./publication
      dockerfile: ./Dockerfile
      args:
        DB_PORT: 27017
    restart: on-failure
    ports:
      - "3001:3000"
    networks:
      - api
    depends_on:
      - publicationdb
    links:
      - publicationdb
    volumes:
      - ./publication:/home/www/webapp
      - /home/www/webapp/node_modules
  # user product service
  user-db:
    container_name: user-db
    image:  postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    ports:
      - 7200:5432
    restart: on-failure
    networks:
      - api
  publicationdb:
    container_name: publication-db
    image:  mongo:latest
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: publication
      MONGO_INITDB_USERNAME: root
      MONGO_INITDB_PASSWORD: root
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - api
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: yecodeo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      # WAIT_HOSTS: users_db:27017
    restart: on-failure
    ports:
      - 8081:80
    depends_on:
      - user-db
    links:
      - user-db
    networks:
      - api
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata: {}
  pgadmin: {}
  mongodata: {}
networks:
  api:
    driver: bridge
