version: "3.8"
services:
  users-service:
    container_name: webapp
    build: 
      context: ./users
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - api
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./users:/home/www/webapp
      - /home/www/webapp/node_modules
  postgres:
    container_name: postgres
    image:  postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    ports:
      - 7200:5432
    restart: on-failure
    networks:
      - api
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: yecodeo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      # WAIT_HOSTS: users_db:27017
    restart: on-failure
    ports:
      - 8081:80
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - api
    volumes:
      - pgadmin:/pgadmin
volumes:
  pgdata: {}
  pgadmin: {}
networks:
  api:
    driver: bridge
