version: "3"
services:
  users-service:
    container_name: webapp
    build: 
      context: ./users
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - users_db
    links:
      - users_db
    volumes:
      - ./users:/home/www/webapp
      - /home/www/webapp/node_modules
  users_db:
    container_name: mongoDb
    image:  mongo:latest
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=users
    ports:
      - 0.0.0.0:7200:27017
    restart: on-failure
    networks:
      - network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: users_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - users_db
    links:
      - users_db
    networks:
      - network

volumes:
  db-data: {}
networks:
  network:
    driver: bridge
