version: "3.1"
services:
  users-service:
    build: 
      context: .
      dockerfile: ./users/Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - users_db
    links:
      - users_db
    volumes:
      - './users:/app'
    environment:
      - DB_URI=mongodb://root:root@users_db:7200/users
  users_db:
    image:  mongo:latest
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=users
    ports:
      - 7200:27017
    restart: on-failure
    networks:
      - network

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: users_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - users_db
    links:
      - users_db
    networks:
      - network

volumes:
  db-data: {}
networks:
  network:
    driver: bridge
